version: '3'
services:
  telegram_bot:
    build: .
    container_name: telegram-search-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data.db:/app/data.db
    ports:
      - "8080:8080"
